sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
branches:
  only:
    - master
before_install:
  - npm config set //$NPM_FEED/:_authToken $NPM_TOKEN
script:
  - npm run lint
  - npm run test
after_success:
  - npx travis-deploy-once --pro "npm run build && npx semantic-release"

services:
  - memcached
  - redis
  - postgresql

compiler: clang-3.6
env:
  - CXX=clang-3.6 KAFKA_PLEASE_LOG=verbose
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - clang
