sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
branches:
  only:
    - master
before_install:
  - npm config set //$NPM_FEED/:_authToken $NPM_TOKEN
  - npm config set //artifactory.zocdoc-ci.com/artifactory/api/npm/npm/:_password $ARTIFACTORY_PASSWORD
  - npm config set //artifactory.zocdoc-ci.com/artifactory/api/npm/npm/:username travis-npm
  - npm config set //artifactory.zocdoc-ci.com/artifactory/api/npm/npm/:email cirobot1@zocdoc.com
script:
  - npm test
after_success:
  - npx travis-deploy-once --pro "npm run build && npx semantic-release"

services:
  - memcached
  - redis
  - postgresql

compiler: clang-3.6
env:
  - CXX=clang-3.6 KAFKA_PLEASE_LOG=verbose
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - clang
